# docker-compose file

# postgres 
# pgadmin


version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD", "pg_isready -U postgres", "auth"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s



  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - 5050:80
      - 5051:443



volumes:
  postgres_data: